- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'binance-tracker'
    - '--image=gcr.io/binance-price-tracker-457613/binance-tracker'
    - '--platform=managed'
    - '--region=asia-east1'
    - '--update-secrets=GOOGLE_SHEET_CREDS_JSON=google-sheet-creds:latest,TELEGRAM_TOKEN=telegram-token:latest,TELEGRAM_CHAT_ID=telegram-chat-id:latest'
