steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/binance-price-tracker-457613/binance-tracker', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/binance-price-tracker-457613/binance-tracker']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'binance-tracker'
  - '--image'
  - 'gcr.io/binance-price-tracker-457613/binance-tracker'
  - '--region'
  - 'asia-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
