options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/binance-price-tracker-457613/binance-tracker', '.']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy binance-tracker \
          --image gcr.io/binance-price-tracker-457613/binance-tracker \
          --platform managed \
          --region asia-east1 \
          --allow-unauthenticated
