name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Docker image
        run: |
          docker build -t gcr.io/binance-price-tracker-457613/binance-tracker:latest .
          docker push gcr.io/binance-price-tracker-457613/binance-tracker:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy binance-tracker \
            --image gcr.io/binance-price-tracker-457613/binance-tracker:latest \
            --platform managed \
            --region asia-east1 \
            --update-secrets GOOGLE_SHEET_CREDS_JSON=google-sheet-creds:latest,TELEGRAM_TOKEN=telegram-token:latest,TELEGRAM_CHAT_ID=telegram-chat-id:latest \
            --allow-unauthenticated
