name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # 如果你的分支叫 main，這裡改成 main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: binance-price-tracker-457613
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml
