name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: binance-price-tracker-457613

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy binance-tracker \
            --project=binance-price-tracker-457613 \
            --region=asia-east1 \
            --source=. \
            --platform=managed \
            --allow-unauthenticated
