name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: binance-price-tracker-457613

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/binance-price-tracker-457613/binance-tracker

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy binance-tracker \
            --image gcr.io/binance-price-tracker-457613/binance-tracker \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated
